name: My First Workflow

on: 
  push:
    branches: 
      - main

jobs:
  MyFirstJob:
    runs-on: self-hosted

    steps:
      - run: echo ";wave; Hello World"
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - run: echo "The repository name is ${{ github.repository }}"
    
  
