name: "Snyk Code Test"

on:
  workflow_dispatch:
  
jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: self-hosted
        
    steps:
    - name: Fetch secret from AWS Secrets Manager
      id: fetch-secret
      run: |
        secret_value=$(aws secretsmanager get-secret-value --secret-id SNYK_API_TOKEN --query SecretString --output text)
        echo "::add-mask::$secret_value"
        echo "SECRET_VALUE=${secret_value}" >> $GITHUB_ENV
        
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Install Snyk
    - name: Install Snyk
      run: sudo npm install -g snyk
    # Authenticate Snyk
    - name: Authenticate Snyk
      run: snyk auth ${SECRET_VALUE}
    # Run Snyk Code
    - name: Run Snyk Code
      run: |
         # snyk code test --sarif
         snyk code test --sarif-file-output=snyk-sarif-report.sarif
      continue-on-error: true
    - name: Upload SARIF Report
      uses: actions/upload-artifact@v3
      with:
        name: snyk-sarif-report
        path: snyk-sarif-report.sarif
    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-sarif-report.sarif

