name: "Snyk Code Test"

on:
  workflow_dispatch:
  
jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    # env: 
      # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}SNYK
      # SNYK_TOKEN: $(aws secretsmanager get-secret-value --secret-id SNYK_API_TOKEN | jq .SecretString)
      
    
       
    steps:
    - name: check-user
      run: whoami
    - name: Set up AWS CLI
      run: |
        export AWS_DEFAULT_REGION=us-west-2
        export AWS_SDK_LOAD_CONFIG=1
   
    - name: Test AWS CLI
      run: aws sts get-caller-identity --debug
    # - name: check-snyk-token
    #  run: aws secretsmanager get-secret-value --secret-id SNYK_API_TOKEN --query 'SecretString' --output text

    - name: Fetch secret from AWS Secrets Manager
      id: fetch-secret
      run: |
        secret_value=$(aws secretsmanager get-secret-value --secret-id SNYK_API_TOKEN --query SecretString --output text)
        echo "SECRET_VALUE=${secret_value}" >> $GITHUB_ENV
        
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SECRET_VALUE}
    # Run Snyk Code
    - name: Run Snyk Code
      run: |
         snyk code test  
      continue-on-error: true
