name: "Snyk Code Test"

on:
  workflow_dispatch:
  
jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}SNYK
      SNYK_TOKEN: $(aws secretsmanager get-secret-value --secret-id SNYK_API_TOKEN | jq .SecretString)
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         echo ${SNYK_TOKEN}
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}
    # Run Snyk Code
    - name: Run Snyk Code
      run: |
         snyk code test  
      continue-on-error: true
