name: "Snyk SAST Test"

on:
  workflow_dispatch:
  
jobs:
  Pipeline-Job:
    # Configure Environment
    runs-on: self-hosted
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4
    # Scan with Snyk
    - name: 'Snyk Test'
      uses: ./
