name: Test Action In Market Place
on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:

      - name: Run my own contianer action
        id: action
        uses: Mkumar2022-7/MyActionInAction@v1.0.0  
        with:
          who-to-greet: '@Mkumar2022-7'
          
      - name: Output the answer
        run: echo "The answer is ${{ steps.action.outputs.answer }}"
